import { DEFAULT_CALCULATORS } from './calculatorLogic.js';

import { firms, affiliateFirms, comparisonFirms, firmBySlug } from './data/firms.js';

function money(n){
  if(!Number.isFinite(n)) return '$0';
  const abs = Math.abs(n);
  return `${n < 0 ? '-' : ''}$${abs.toLocaleString(undefined,{maximumFractionDigits:0})}`;
}
function num(id){ return parseFloat(document.getElementById(id)?.value || 0); }
function riskClass(score){ return score >= 84 ? 'green' : score >= 78 ? 'amber' : ''; }
function verificationClass(f){ return f.verification === 'official' ? 'green' : f.verification === 'research-snapshot' ? 'amber' : ''; }
function verificationLabel(f){ return f.verification === 'official' ? 'Source reviewed' : f.verification === 'research-snapshot' ? 'Source review updated' : 'Source review needed'; }
function isRecommended(f){ return f.affiliate === true; }
function recommendationBadge(f){ return isRecommended(f) ? '<span class="pill green">Recommended</span>' : ''; }
function affiliatePrimaryLabel(f){ return f.affiliateUrl ? 'Check current offer' : 'Visit official site'; }
function affiliateHref(f){ return f.affiliateUrl || f.officialUrl; }
function couponText(f){ return f.couponCode ? `<span class="pill amber">Code to try: ${f.couponCode}</span>` : '<span class="pill">No public code listed</span>'; }
function affiliateActions(f, details=true){
  const rel=f.affiliateUrl ? 'sponsored noreferrer' : 'noreferrer';
  const source=f.affiliateUrl ? 'affiliate' : 'official-fallback';
  const detailsBtn=details ? `<a class="btn small" href="/firms/${f.id}/">Compare rules</a>` : '';
  return `<div class="affiliate-actions"><a class="btn primary small outbound" href="${affiliateHref(f)}" target="_blank" rel="${rel}" data-outbound-firm="${f.id}" data-outbound-source="${source}">${affiliatePrimaryLabel(f)}</a>${detailsBtn}</div>`;
}
function affiliateCard(f){
  if(isRecommended(f)){
    return `<div class="article-card affiliate-card"><h2>Recommended offer</h2><p>${recommendationBadge(f)} ${couponText(f)}</p><p>Use the link below to check ${f.name}. Confirm the final checkout price, offer terms, and current rules before buying.</p>${affiliateActions(f,false)}</div>`;
  }
  if(f.affiliateUrl){
    return `<div class="article-card affiliate-card"><h2>Current offer</h2><p>${couponText(f)}</p><p>Use this link if you choose ${f.name}, then confirm current prices, rules, promos, and account availability before buying.</p>${affiliateActions(f,false)}</div>`;
  }
  return `<div class="article-card affiliate-card"><h2>Official source</h2><p>${couponText(f)}</p><p>Use the official firm site for current prices, rules, promos, and account availability.</p>${affiliateActions(f,false)}</div>`;
}
function firmTraits(f){
  const hay = `${f.name} ${f.category} ${f.best} ${f.price} ${f.drawdown} ${f.daily} ${f.payout} ${f.fit}`.toLowerCase();
  const tags = [];
  if(isRecommended(f)) tags.push('Recommended');
  if(hay.includes('eod')) tags.push('EOD drawdown');
  if(hay.includes('static')) tags.push('Static drawdown');
  if(hay.includes('no activation') || hay.includes('activation fee: free') || hay.includes('free activation')) tags.push('No activation fee');
  if(hay.includes('daily') || hay.includes('fast') || hay.includes('1 day') || hay.includes('one-day')) tags.push('Fast payout/pass');
  if(hay.includes('direct') || hay.includes('lightning')) tags.push('Direct funded option');
  if(hay.includes('overnight') || hay.includes('swing')) tags.push('Swing-friendly');
  return [...new Set(tags)].slice(0,4);
}
function firmMatches(f, filter){
  if(!filter || filter === 'all') return true;
  const hay = `${f.name} ${f.category} ${f.best} ${f.price} ${f.drawdown} ${f.daily} ${f.payout} ${f.fit}`.toLowerCase();
  if(filter === 'recommended') return isRecommended(f);
  if(filter === 'eod') return hay.includes('eod');
  if(filter === 'static') return hay.includes('static');
  if(filter === 'fast') return hay.includes('daily') || hay.includes('fast') || hay.includes('1 day') || hay.includes('one-day') || hay.includes('5 days');
  if(filter === 'noactivation') return hay.includes('no activation') || hay.includes('activation fee: free') || hay.includes('free activation') || hay.includes('$0 activation');
  return true;
}
function finderRecommendation(goal){
  const map={
    cheapest:'bulenox',
    fast:'lucidtraderfunding',
    eod:'lucidtraderfunding',
    static:'phidias',
    structured:'earn2trade',
    flexible:'daytraders'
  };
  return firms.find(f=>f.id===(map[goal]||'lucidtraderfunding')) || firms[0];
}

function pageShell(content){
  return `
    <header class="nav">
      <div class="wrap nav-inner">
        <a class="brand" href="/" aria-label="Futures Prop Edge home"><span class="brand-mark"></span><span>Futures Prop Edge</span></a>
        <nav class="nav-links" aria-label="Primary">
          <a href="/compare/">Compare Firms</a><a href="/checklist/">Checklist</a><a href="/calculators/">Calculators</a><a href="/#guides">Guides</a><a href="/firms/">Firm Guides</a><a href="/disclaimers/">Disclosures</a>
        </nav>
        <div class="nav-cta"><a class="btn" href="/checklist/">Free checklist</a><a class="btn primary" href="/compare/">Compare firms</a><button class="btn mobile-menu" id="menuBtn" aria-controls="mobileNav" aria-expanded="false">Menu</button></div>
      </div>
      <div class="wrap mobile-nav-drawer" id="mobileNav" hidden><a href="/compare/">Compare firms</a><a href="/checklist/">Checklist</a><a href="/calculators/">Calculators</a><a href="/#guides">Guides</a><a href="/firms/">Firm guides</a><a href="/disclaimers/">Disclosures</a></div>
    </header>
    <main>${content}</main>
    <div class="sticky-tools"><a class="btn small" href="/calculators/">Calculator</a><button class="btn small" id="copyLink">Copy link</button></div>
    <div class="tooltip-pop" id="tooltipPop" role="tooltip"></div>
    <div class="toast" id="toast">Link copied</div>
      <footer class="footer"><div class="wrap footer-grid"><div><div class="brand"><span class="brand-mark"></span><span>Futures Prop Edge</span></div><p class="disclaimer">Built for futures traders comparing funded account rules. We focus on NQ/MNQ risk, drawdown mechanics, and practical rule clarity.</p></div><div><b>Tools</b><p class="disclaimer"><a href="/compare/">Comparison table</a><br><a href="/checklist/">NQ checklist</a><br><a href="/calculators/">Drawdown calculator</a><br><a href="/best-nq-prop-firms.html">Best NQ prop firms</a><br><a href="/lucid-trading-vs-apex-nq-traders.html">Lucid vs Apex</a><br><a href="/best-eod-drawdown-prop-firms-nq-traders.html">Best EOD drawdown firms</a></p></div><div><b>Important</b><p class="disclaimer">Educational only. Not financial advice. Prop firm rules change; always verify on official websites before buying.<br><a href="/disclaimers/">Disclosures</a> | <a href="/privacy/">Privacy</a> | <a href="/terms/">Terms</a></p></div></div></footer>
  `;
}

function renderHome(){
  return `
  ${topMarketTape()}
  <section class="hero"><div class="wrap hero-grid">
    <div>
      <div class="eyebrow"><span class="dot"></span>Built for NQ / MNQ funded futures traders</div>
      <h1>Choose the right prop firm before the <span class="grad">drawdown trap</span> gets you.</h1>
      <p class="lead">Compare funded futures accounts, calculate trailing drawdown risk, size NQ trades correctly, and find current offers without digging through scattered rule pages.</p>
      <div class="hero-actions"><a class="btn primary" href="/calculators/">Start with risk calculator</a><a class="btn" href="/compare/">Compare firms</a><a class="btn" href="/checklist/">Get checklist</a></div>
      <div class="mini-proof"><span><b>9</b> covered firms</span><span><b>3</b> calculators</span><span><b>NQ-first</b> examples</span><span><b>Current offers</b> clearly labeled</span></div>
    </div>
    <div class="hero-offers" aria-label="Current prop firm discounts">
      <div class="hero-offers-head"><span>Current discounts</span><b>Click an offer to open it directly</b></div>
      ${offerBanners()}
    </div>
  </div></section>
  ${startPathSection()}
  ${guidesSection()}
  ${comparisonSection(false)}
  ${leadMagnetSection()}
  ${calculatorSection()}
  <section class="section"><div class="wrap cta-band"><div><div class="eyebrow"><span class="dot"></span>Built for futures traders</div><h2>Compare rules before you buy an account.</h2><p class="subhead">Use the finder, firm guides, and calculators to check drawdown, payout, daily-loss, and risk rules before choosing a funded futures account.</p></div><a class="btn primary" href="/disclaimers/">Review disclosures</a></div></section>`;
}

function topMarketTape(){
  return `<section class="top-market-tape" aria-label="Market context for S&P 500, Nasdaq 100, gold, and crude oil"><div class="wrap top-market-inner"><div class="top-market-label"><span class="dot"></span><b>Market context</b><small>ES / NQ / GC / CL</small></div><div class="market-tape-widget" id="marketTapeWidget"><tv-ticker-tape symbols="FOREXCOM:SPXUSD,FOREXCOM:NSXUSD,CMCMARKETS:GOLD,TVC:USOIL"></tv-ticker-tape><div class="market-tape-loading">Loading market tape...</div></div><span class="top-market-note">Indicative only</span></div></section>`;
}

function startPathSection(){
  const steps = [
    { href:'/calculators/', label:'1', title:'Check account risk', text:'Convert NQ/MNQ stop size into dollars before choosing an account.' },
    { href:'/compare/', label:'2', title:'Compare rule fit', text:'Filter by drawdown, payout path, activation fees, and NQ-friendly rules.' },
    { href:'/checklist/', label:'3', title:'Use the checklist', text:'Download the pre-check before you use an offer or buy a challenge.' }
  ];
  return `<section class="start-path wrap" aria-label="Suggested first steps">${steps.map(step=>`<a href="${step.href}"><span>${step.label}</span><div><b>${step.title}</b><em>${step.text}</em></div></a>`).join('')}</section>`;
}

function offerBanners(){
  const offers = [
    { id:'lucidtraderfunding', headline:'Lucid Trading', discount:'50% off all accounts', detail:'Includes LucidDirect', code:'DUTRADING', expires:'Valid through July 2 at 5 PM ET', featured:true },
    { id:'phidias', headline:'Phidias Propfirm', discount:'80% off', detail:'OTP accounts', code:'DUTRADING' },
    { id:'alphafutures', headline:'Alpha Futures', discount:'25% off', detail:'Premium accounts', code:'Duckens026406' },
    { id:'daytraders', headline:'DayTraders', discount:'80% off', detail:'Check current eligible account pricing', code:'TNTIQNUL' },
    { id:'legendstrading', headline:'The Legends Trading', discount:'50% / 30% off', detail:'Apprentice / Elite plans', code:'DUTRADING' },
    { id:'bulenox', headline:'Bulenox', discount:'89% off', detail:'Option 1 accounts', code:'dutrading' },
    { id:'earn2trade', headline:'Earn2Trade', discount:'60% off', detail:'Current Trader Career Path pricing', code:'dutrading' }
  ];
  return `<div class="promo-grid">${offers.map(offer=>{
    const firm = firms.find(f=>f.id === offer.id);
    return `<a class="promo-banner promo-${offer.id}${offer.featured ? ' featured' : ''}" href="${affiliateHref(firm)}" target="_blank" rel="sponsored noreferrer" aria-label="${offer.headline}: ${offer.discount}. Opens in a new tab" data-outbound-firm="${firm.id}" data-outbound-source="offer-banner"><div class="promo-banner-top"><span>${offer.headline}</span><b>Open offer</b></div><strong class="offer-discount">${offer.discount}</strong><p>${offer.detail}</p><div class="promo-banner-bottom"><span>Code to try: ${offer.code}</span>${offer.expires ? `<em>${offer.expires}</em>` : ''}</div></a>`;
  }).join('')}</div>`;
}

function guidesSection(){
  const guides = [
    { href:'/best-nq-prop-firms.html', label:'Best NQ Prop Firms', text:'A practical shortlist for NQ/MNQ traders comparing drawdown, payout, and rule fit.', cta:'Read guide' },
    { href:'/lucid-trading-vs-apex-nq-traders.html', label:'Lucid vs Apex', text:'A direct rule-fit comparison: Lucid for cleaner EOD rules, Apex for account-scale context.', cta:'Compare rules' },
    { href:'/best-eod-drawdown-prop-firms-nq-traders.html', label:'Best EOD Drawdown Firms', text:'Use this before buying if intraday trailing drawdown keeps catching normal NQ trades.', cta:'See EOD guide' }
  ];
  return `<section class="section guide-strip" id="guides"><div class="wrap"><div class="section-head"><div><span class="eyebrow"><span class="dot"></span>NQ Prop Firm Guides</span><h2>Rule guides that support the comparison.</h2><p class="subhead">These pages give visitors more context, then point them back to the calculators, comparison table, checklist, and current offers before they buy.</p></div><a class="btn primary" href="/compare/">Compare firms</a></div><div class="guide-grid">${guides.map(guide=>`<a class="guide-card" href="${guide.href}"><span class="pill">Guide</span><h3>${guide.label}</h3><p>${guide.text}</p><b>${guide.cta}</b></a>`).join('')}</div></div></section>`;
}

function leadMagnetSection(){
  return `<section class="section lead-magnet" id="checklist"><div class="wrap lead-grid"><div class="lead-copy"><span class="eyebrow"><span class="dot"></span>Free NQ prop firm checklist</span><h2>Before you buy another challenge, run through the drawdown traps first.</h2><p class="subhead">Download a practical checklist for NQ/MNQ traders: EOD vs intraday drawdown, daily loss limits, consistency rules, payout buffers, activation fees, and account-size risk.</p><div class="checklist-preview"><div><b>1</b><span>Confirm the drawdown type before comparing prices.</span></div><div><b>2</b><span>Calculate NQ/MNQ stop risk against daily loss and cushion.</span></div><div><b>3</b><span>Check payout rules, consistency %, activation fees, and reset costs.</span></div><div><b>4</b><span>Use offers only after rechecking live checkout terms.</span></div></div></div><form class="lead-form" id="leadForm"><h3>Unlock the printable checklist</h3><p>Enter your email to join Futures Prop Edge and unlock the NQ Prop Firm Risk Checklist instantly. You can unsubscribe anytime.</p><label>Email address</label><input id="leadEmail" name="email" type="email" autocomplete="email" placeholder="you@example.com" required><label>Trading focus</label><select id="leadFocus" name="focus"><option value="NQ/MNQ prop firm challenges">NQ/MNQ prop firm challenges</option><option value="EOD drawdown accounts">EOD drawdown accounts</option><option value="Firm offers / comparison">Firm offers / comparison</option><option value="Risk sizing calculators">Risk sizing calculators</option></select><button class="btn primary" type="submit">Join list + unlock checklist</button><p class="lead-status" id="leadStatus">Instant checklist access plus occasional rule and promo updates. No spam; unsubscribe anytime. Educational only, not financial advice.</p><div class="download-card" id="checklistDownload" hidden><b>Checklist unlocked.</b><span>Open the printable checklist guide and keep comparing firms on the site.</span><a class="btn small" id="openChecklist" href="/nq-prop-firm-risk-checklist.html" target="_blank" rel="noopener">Open printable checklist</a></div></form></div></section>`;
}
function comparisonSection(full=true){
  const rows = firms.map(f=>`<tr data-firm-row data-tags="${firmTraits(f).join(' ').toLowerCase()}"><td><strong>${f.name}</strong><br><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span>${recommendationBadge(f)}</td><td><strong>${f.category}</strong><br><span class="muted-small">${f.best}</span></td><td>${f.price}</td><td>${f.drawdown}</td><td>${f.daily}</td><td>${affiliateActions(f,true)}</td></tr>`).join('');
  const cards = firms.map(f=>`<article class="finder-card" data-firm-card data-firm-name="${f.name.toLowerCase()}" data-filter-match="all ${['recommended','eod','static','fast','noactivation'].filter(x=>firmMatches(f,x)).join(' ')}"><div class="finder-card-top"><div><h3>${f.name}</h3><p>${f.fit}</p></div>${recommendationBadge(f)}</div><div class="finder-tags">${firmTraits(f).map(t=>`<span>${t}</span>`).join('')}</div><div class="finder-stats"><div><small>Drawdown</small><b>${f.drawdown}</b></div><div><small>Payout</small><b>${f.payout}</b></div><div><small>Cost note</small><b>${f.price}</b></div></div><div class="finder-actions">${affiliateActions(f,true)}</div></article>`).join('');
  return `<section class="section" id="compare"><div class="wrap"><div class="section-head"><div><h2>Find and compare futures prop firms.</h2><p class="subhead">Use the finder to narrow accounts by what matters: recommended firms, EOD/static drawdown, fast payout paths, activation fees, and NQ-friendly risk rules.</p></div>${full?'<a class="btn" href="/calculators/">Check risk</a>':''}</div><div class="finder-panel"><div class="finder-copy"><span class="eyebrow"><span class="dot"></span>Prop firm finder</span><h3>Pick your priority. Get a practical starting point.</h3><p>Not every trader needs the same firm. Choose your main goal and the finder highlights the closest match from the firms covered in this guide.</p><select id="finderGoal"><option value="fast">Fast payout / live-capital path</option><option value="cheapest">Lowest displayed starting cost</option><option value="eod">EOD drawdown preferred</option><option value="static">Static drawdown / no trailing</option><option value="structured">Structured legacy evaluation</option><option value="flexible">Flexible payout-policy choice</option></select></div><div class="finder-result" id="finderResult"></div></div><div class="compare-toolbar"><div class="filter-buttons" role="group" aria-label="Compare filters"><button class="filter-chip active" data-filter="all">All firms</button><button class="filter-chip" data-filter="recommended">Recommended</button><button class="filter-chip" data-filter="eod">EOD drawdown</button><button class="filter-chip" data-filter="static">Static</button><button class="filter-chip" data-filter="fast">Fast payout</button><button class="filter-chip" data-filter="noactivation">No activation fee</button></div><input id="firmSearch" class="firm-search" type="search" placeholder="Search firm, drawdown, payout..."></div><div class="finder-grid">${cards}</div><details class="table-details" ${full?'open':''}><summary>Open full comparison table</summary><div class="table-wrap"><table><thead><tr><th>Firm</th><th>Category</th><th>Price</th><th>Drawdown</th><th>Daily loss</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></details></div></section>`;
}

function renderCompare(){ return comparisonSection(true); }
function renderChecklist(){ return `${leadMagnetSection()}${calculatorSection()}`; }

function calculatorSection(){
  return `<section class="section" id="calculators"><div class="wrap"><div class="section-head"><div><h2>Free calculators for prop firm risk.</h2><p class="subhead">Pressure-test drawdown, consistency rules, futures stop risk, and challenge pace before choosing an account.</p></div></div><div class="calc-grid"><div class="tabs"><button class="tab active" data-calc="drawdown"><b>Trailing drawdown + consistency</b><br>Calculate liquidation cushion and 30/40/50% consistency rules.</button><button class="tab" data-calc="nq"><b>Futures risk</b><br>NQ, MNQ, ES, GC, and CL stop-risk calculator.</button><button class="tab" data-calc="planner"><b>Challenge pass planner</b><br>Estimate daily target and risk pace.</button></div><div class="calculator" id="calcPanel"></div></div></div></section>`;
}
function renderCalculators(){ return calculatorSection(); }

function drawdownCalc(){const d=DEFAULT_CALCULATORS.drawdown;return `<h3>Trailing drawdown + consistency simulator</h3><p class="disclaimer">Enter the account state and the firm's consistency percentage. Many prop firms require your biggest winning day to be no more than 30%, 40%, or 50% of total profit before payout.</p><div class="form-grid"><div><label>Starting balance</label><input id="startBal" type="number" value="${d.startBal}"></div><div><label>Current balance</label><input id="currentBal" type="number" value="${d.currentBal}"></div><div><label>High-water mark <button class="help-dot" type="button" data-help="High-water mark is the highest balance or equity your account has reached so far. For Apex-style EOD drawdown, use the highest end-of-day closing balance, not the highest intraday unrealized spike. Example: if the EOD high-water mark is $52,400 and the trail is $2,500, the liquidation level is $49,900." aria-label="What is high-water mark?">?</button></label><input id="highBal" type="number" value="${d.highBal}"></div><div><label>Drawdown amount</label><input id="ddAmount" type="number" value="${d.ddAmount}"></div><div><label>Drawdown type</label><select id="ddType"><option value="trailing">Intraday trailing</option><option value="eod">EOD trailing (Apex-style)</option><option value="static">Static from start</option></select></div><div><label>Consistency rule %</label><input id="consistencyPct" type="number" value="${d.consistencyPct}" min="1" max="100" step="1"></div><div><label>Total profit so far</label><input id="totalProfit" type="number" value="${d.totalProfit}"></div><div><label>Best winning day</label><input id="bestDay" type="number" value="${d.bestDay}"></div></div><div class="calc-actions"><button class="btn small" type="button" data-reset-calc="drawdown">Reset calculator</button></div><div class="result-box" id="ddResults"></div><div class="note" id="ddNote"></div>`}
function nqCalc(){const d=DEFAULT_CALCULATORS.nq;return `<h3>Futures position risk calculator</h3><p class="disclaimer">Choose the futures contract and enter your stop size. Point values used: NQ $20, MNQ $2, ES $50, GC $100, and CL $1,000 per point per contract.</p><div class="form-grid"><div><label>Market</label><select id="market"><option value="20" data-symbol="NQ" data-step="0.25">NQ - Nasdaq 100</option><option value="2" data-symbol="MNQ" data-step="0.25">MNQ - Micro Nasdaq</option><option value="50" data-symbol="ES" data-step="0.25">ES - S&P 500</option><option value="100" data-symbol="GC" data-step="0.1">GC - Gold</option><option value="1000" data-symbol="CL" data-step="0.01">CL - Crude Oil</option></select></div><div><label>Contracts</label><input id="contracts" type="number" value="${d.contracts}"></div><div><label>Stop size in points</label><input id="stopPts" type="number" value="${d.stopPts}" step="0.25"></div><div><label>Daily loss limit</label><input id="dailyLoss" type="number" value="${d.dailyLoss}"></div><div><label>Drawdown cushion</label><input id="cushion" type="number" value="${d.cushion}"></div><div><label>Profit target</label><input id="target" type="number" value="${d.target}"></div></div><div class="calc-actions"><button class="btn small" type="button" data-reset-calc="nq">Reset calculator</button></div><div class="result-box" id="nqResults"></div><div class="note" id="nqNote"></div>`}
function plannerCalc(){const d=DEFAULT_CALCULATORS.planner;return `<h3>Challenge pass planner</h3><p class="disclaimer">Plan a conservative pace instead of trying to pass in one overleveraged day.</p><div class="form-grid"><div><label>Profit target</label><input id="profitTarget" type="number" value="${d.profitTarget}"></div><div><label>Days to pass</label><input id="days" type="number" value="${d.days}"></div><div><label>Max daily loss</label><input id="maxDailyLoss" type="number" value="${d.maxDailyLoss}"></div><div><label>Risk per trade</label><input id="riskTrade" type="number" value="${d.riskTrade}"></div></div><div class="calc-actions"><button class="btn small" type="button" data-reset-calc="planner">Reset calculator</button></div><div class="result-box" id="planResults"></div><div class="note" id="planNote"></div>`}

function renderFirms(firmId){
  const hash = firmId;
  if(hash){
    const f=firms.find(x=>x.id===hash) || firms[0];
    if(f.id==='apex') return renderApexArticle(f);
    if(f.id==='phidias') return renderPhidiasArticle(f);
    if(f.id==='bulenox') return renderBulenoxArticle(f);
    if(f.id==='lucidtraderfunding') return renderLucidArticle(f);
    if(f.id==='alphafutures') return renderAlphaFuturesArticle(f);
    if(f.id==='daytraders') return renderDayTradersArticle(f);
    if(f.id==='legendstrading') return renderLegendsTradingArticle(f);
    if(f.id==='earn2trade') return renderEarn2TradeArticle(f);
    return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>${f.name} for futures traders</h1><p class="lead">${f.fit}</p><div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official source: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">${f.officialUrl}</a></p><p class="disclaimer">Use this firm page as a quick rule overview, then confirm current pricing, restrictions, and payout terms on the official website.</p></div><div class="article-card"><h2>Rules in plain English</h2><p>Before choosing ${f.name}, confirm current evaluation prices, profit targets, drawdown mechanics, payout rules, activation fees, reset fees, consistency rules, contract limits, and prohibited strategies on the official website.</p><ul><li>Category: ${f.category}</li><li>Typical risk level: ${f.risk}</li><li>Price: ${f.price}</li><li>Profit target: ${f.target}</li><li>Drawdown note: ${f.drawdown}</li><li>Daily loss: ${f.daily}</li><li>Payout note: ${f.payout}</li></ul></div><div class="article-card"><h2>How NQ traders usually fail</h2><p>The common failure pattern is oversizing NQ contracts while the trailing drawdown is still close to the current balance. Use MNQ until the cushion is large enough, then scale only after the account has room.</p><a class="btn primary" href="/calculators/">Run calculator for this account</a></div></article>`;
  }
  return `<section class="section"><div class="wrap"><div class="section-head"><div><h2>Futures prop firm rule guides.</h2><p class="subhead">Use these firm guides to compare drawdown, payout, pricing, and account-fit details before choosing where to spend money.</p></div></div><div class="firm-grid">${firms.map(f=>`<a class="firm" href="/firms/${f.id}/"><div class="firm-top"><div><h3>${f.name}</h3><p>${f.fit}</p></div><span class="status-dot ${verificationClass(f)}"></span></div><div class="firm-meta"><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span>${recommendationBadge(f)}<span class="pill">${f.category}</span></div></a>`).join('')}</div></div></section>`;
}


function renderPhidiasArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>Phidias Propfirm: Phidias 2.0 rules for futures traders</h1><p class="lead">Phidias recently relaunched its program as Phidias 2.0: Express to Live static-drawdown accounts, Fundamental EOD accounts, and Premium swing-capable accounts with overnight/weekend holds and a progressive profit split.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official sources: <a href="https://phidiaspropfirm.com/phidias-2-0" target="_blank" rel="noreferrer">Phidias 2.0 page</a>, <a href="https://phidiaspropfirm.com/accounts" target="_blank" rel="noreferrer">accounts</a>, <a href="https://phidiaspropfirm.com/rules" target="_blank" rel="noreferrer">rules</a>, and <a href="https://phidiaspropfirm.com/affiliate-program" target="_blank" rel="noreferrer">affiliate program</a>.</p><p class="disclaimer">Phidias rules and offers can change. Try code DUTRADING if you use the link, then confirm the final checkout price and current account rules before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>What changed in Phidias 2.0</h2><ul><li>Three main account families: Express to Live, Fundamental, and Premium.</li><li>New platform lineup: Tradovate, NinjaTrader, and TradingView execution were added alongside Rithmic and DeepCharts.</li><li>Express to Live is now the flagship fast path: static drawdown, 0 minimum trading days, no consistency rule, and first payout can convert the account toward LIVE.</li><li>Premium replaces the old swing-style path with overnight/weekend holding, 1-day evaluation minimum, 5-day funded payout cadence, progressive 75% to 100% profit split, and one Cash Account Reset option.</li><li>Phidias states $15M+ paid to traders, zero denied payouts, and 90% of payouts processed under 30 minutes; treat these as official marketing claims to verify over time.</li></ul></div>
  <div class="article-card"><h2>Express to Live account grid</h2><p class="disclaimer">E2L is the most interesting Phidias product for fast NQ traders because the drawdown is static and never trails.</p><div class="table-wrap"><table><thead><tr><th>Size</th><th>Profit target</th><th>Static drawdown</th><th>Bonus payout</th><th>LIVE credit</th><th>Max minis / micros</th></tr></thead><tbody><tr><td>25K E2L</td><td>$1,500</td><td>$500</td><td>$1,000</td><td>$500</td><td>2 / 20</td></tr><tr><td>50K E2L</td><td>$2,500</td><td>$650</td><td>$2,000</td><td>$1,000</td><td>5 / 50</td></tr><tr><td>100K E2L</td><td>$3,500</td><td>$800</td><td>$3,000</td><td>$1,500</td><td>7 / 70</td></tr><tr><td>150K E2L</td><td>$4,500</td><td>$1,000</td><td>$4,500</td><td>$2,000</td><td>9 / 90</td></tr></tbody></table></div><ul><li>Common E2L rules: static drawdown, 0 minimum trading days, no consistency rule, no daily loss limit, news trading authorized, and up to 5 E2L accounts per trader.</li><li>Overnight/weekend positions are not permitted on E2L.</li><li>Liquidation threshold equals initial capital minus static drawdown.</li></ul></div>
  <div class="article-card"><h2>Fundamental vs Premium</h2><div class="table-wrap"><table><thead><tr><th>Feature</th><th>Fundamental</th><th>Premium</th></tr></thead><tbody><tr><td>Sizes</td><td>50K / 100K / 150K</td><td>50K / 100K / 150K</td></tr><tr><td>Drawdown</td><td>EOD trailing</td><td>EOD trailing</td></tr><tr><td>Profit target</td><td>$4,000 / $6,000 / $9,000</td><td>$4,000 / $6,000 / $9,000</td></tr><tr><td>Evaluation minimum days</td><td>3</td><td>1</td></tr><tr><td>Funded payout cadence</td><td>10 qualifying days between payouts</td><td>5 qualifying days between payouts</td></tr><tr><td>Profit split</td><td>80% trader / 20% Phidias</td><td>75%, 80%, 85%, 90%, then 100% from payout 5 onward</td></tr><tr><td>Overnight/weekend</td><td>Not permitted</td><td>Authorized</td></tr><tr><td>Funded consistency</td><td>30% max per day</td><td>30% max per day</td></tr></tbody></table></div><p>Both Fundamental and Premium use EOD trailing drawdown. Phidias says the liquidation level is calculated at the end of the trading day and does not chase intraday unrealized profits, but the current liquidation price is still enforced if the balance reaches the limit.</p></div>
  <div class="article-card"><h2>Fundamental/Premium size rules</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>EOD drawdown</th><th>Target</th><th>Max minis / micros</th><th>Activation fee</th><th>Payout cap</th><th>Withdrawal threshold</th></tr></thead><tbody><tr><td>50K</td><td>$2,500</td><td>$4,000</td><td>10 / 100</td><td>$149</td><td>$2,000</td><td>$52,600</td></tr><tr><td>100K</td><td>$3,000</td><td>$6,000</td><td>14 / 140</td><td>$149</td><td>$2,500</td><td>$103,700</td></tr><tr><td>150K</td><td>$4,500</td><td>$9,000</td><td>17 / 170</td><td>$169</td><td>$2,750</td><td>$154,500</td></tr></tbody></table></div><p class="disclaimer">One-time payment accounts show no activation fee when switching to CASH. Monthly subscription accounts list the activation fees above. Premium also lists a one-time Cash Account Reset option: 50K $399, 100K $499, 150K $599.</p></div>
  <div class="article-card"><h2>Payouts, LIVE path, and trading freedom</h2><ul><li>Minimum withdrawal: $500.</li><li>Fundamental profit split: fixed 80% trader / 20% Phidias.</li><li>Premium split: 75% on payout 1, 80% on payout 2, 85% on payout 3, 90% on payout 4, and 100% from payout 5 onward.</li><li>Express to Live: after passing evaluation, the trader targets a funded CASH payout; the first payout can include bonus payout plus LIVE credit and convert toward a LIVE funded account.</li><li>Fundamental/Premium LIVE transition: discretionary risk-team review after 5 successful payouts or $100,000 cumulative profits across accounts; not guaranteed.</li><li>News trading is authorized on all account types.</li><li>Fundamental and E2L must close before end of day; Premium may hold overnight and over the weekend.</li><li>Phidias allows up to 15 funded accounts at the same time across account families, according to the official accounts FAQ.</li></ul></div>
  <div class="article-card"><h2>NQ trader take</h2><p>For an NQ/MNQ trader, Phidias is worth comparing because E2L removes two common prop-firm traps: intraday trailing drawdown and consistency/minimum-day friction. The tradeoff is tight static drawdown, especially on the 25K and 50K E2L accounts, so MNQ sizing still matters. Premium is the flexible path for swing traders because overnight/weekend holds are allowed, but the funded 30% consistency rule and EOD floor still need to be managed.</p><a class="btn primary" href="/calculators/">Run NQ risk calculator</a></div>
  </article>`;
}

function renderAlphaFuturesArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">All firms</a><h1>Alpha Futures: one-step futures evaluations and account rules</h1><p class="lead">Alpha Futures is a futures evaluation firm with Zero, Premium, Advanced, and Standard challenge paths. Use this guide to compare account type, MLL, payout cap, news rules, and checkout price before buying.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official sources: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">Alpha Futures official site</a>, <a href="https://help.alpha-futures.com/en/articles/11927533-futures-challenge-rules" target="_blank" rel="noreferrer">challenge rules</a>, and <a href="https://help.alpha-futures.com/en/articles/11928417-when-can-i-request-a-performance-fee" target="_blank" rel="noreferrer">performance fee rules</a>.</p><p class="disclaimer">Confirm current account type, MLL, payout cap, news rules, and final checkout price on Alpha Futures before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Alpha Futures account types</h2><p>The official rules page lists Zero, Premium, Advanced, and Standard account types. Zero and Premium show no consistency requirement in the published table. News trading differs by account type, so check the account you choose before trading major releases.</p><div class="table-wrap"><table><thead><tr><th>Account type</th><th>Rule angle</th><th>News trading</th><th>Notes to verify</th></tr></thead><tbody><tr><td>Zero</td><td>Most flexible published rule profile</td><td>Allowed in challenge and master account</td><td>No consistency listed; verify soft breach and position monitoring details</td></tr><tr><td>Premium</td><td>Flexible but stricter news rule</td><td>Not allowed</td><td>No consistency listed; verify payout cap and MLL for chosen size</td></tr><tr><td>Advanced</td><td>Lower displayed starting price than Premium/Zero</td><td>Verify official table</td><td>Confirm strategy, consistency, and payout-cap rules</td></tr><tr><td>Standard</td><td>Common comparison account type</td><td>Verify official table</td><td>Confirm rule restrictions before using NQ size</td></tr></tbody></table></div></div>
  <div class="article-card"><h2>Pricing and checkout notes</h2><ul><li>The official site shows multiple product tabs and account sizes. Current examples include Zero 50K at $119/month and Standard 50K at $139/month.</li><li>The homepage promotes one-step futures evaluations, up to $750K simulated funds, up to 6 accounts, EOD-style drawdown messaging, and no activation fee messaging on Zero accounts.</li><li>Use code ${f.couponCode} only after confirming the final checkout price, terms, and active promotion.</li></ul></div>
  <div class="article-card"><h2>Performance fee rules</h2><ul><li>Alpha Futures says performance fee requests can be made after at least 5 winning days.</li><li>A winning day must close in profit by at least $200.</li><li>The help center says there is no maximum request amount, but requests are manually reviewed before approval.</li><li>Performance fee processing time can depend on team workload, so verify the current payout page before relying on timing.</li></ul></div>
  <div class="article-card"><h2>NQ trader takeaways</h2><p>Alpha Futures is worth comparing if you want a one-step futures evaluation with EOD drawdown language, multiple account types, and no activation fee messaging on Zero accounts. For NQ traders, the account type matters more than the sticker price: verify MLL, payout cap, soft-breach rules, news restrictions, and whether your normal stop size fits the cushion.</p><a class="btn primary" href="/calculators/">Run NQ risk calculator</a></div></article>`;
}


function renderDayTradersArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">All firms</a><h1>DayTraders: futures-only prop firm paths and drawdown rules</h1><p class="lead">DayTraders offers several futures-only routes: standard evaluations, EOD accounts, Static accounts, Straight to Funded, and Straight to Live. Use this guide to compare the drawdown model before choosing a checkout link.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official sources: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">DayTraders official site</a>, <a href="https://daytraders.com/futures-prop-firms" target="_blank" rel="noreferrer">futures prop firm guide</a>, <a href="https://daytraders.com/help/articles/9855052-drawdown-threshold-guide-trailing-static-eod" target="_blank" rel="noreferrer">drawdown guide</a>, <a href="https://daytraders.com/help/articles/14038700-live-accounts-payouts" target="_blank" rel="noreferrer">live payouts</a>, and <a href="https://intercom.help/daytraders/en/articles/13642082-straight-to-funded-s2f-futures" target="_blank" rel="noreferrer">S2F rules</a>.</p><p class="disclaimer">Confirm current account type, drawdown model, payout terms, platform support, and final checkout price on DayTraders before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>DayTraders account paths</h2><p>The official futures prop firm guide describes Trailing, EOD, Static, S2F, and S2L paths. That variety is useful, but it also means traders need to compare the rule model, not just the displayed price.</p><div class="table-wrap"><table><thead><tr><th>Path</th><th>What it means</th><th>Price range shown</th><th>NQ trader note</th></tr></thead><tbody><tr><td>Trailing</td><td>Real-time trailing drawdown based on live balance, including unrealized PnL.</td><td>$249 to $879</td><td>Most sensitive to intraday runners and pullbacks.</td></tr><tr><td>EOD</td><td>End-of-day trailing drawdown that updates after the trading day closes.</td><td>$309 to $1,599</td><td>Often easier to manage than intraday trailing, but DLL still matters.</td></tr><tr><td>Static</td><td>Fixed floor that does not move with profit.</td><td>$150 to $400</td><td>Cleaner rule model, but check target, size, and promotion terms.</td></tr><tr><td>S2F</td><td>Straight to Funded simulated account without completing an evaluation first.</td><td>$370 to $825</td><td>Faster access, but payout eligibility and DLL rules still control risk.</td></tr><tr><td>S2L</td><td>Evaluation path that can lead to live funded accounts with real execution.</td><td>$329 to $599</td><td>Live path uses different payout split and platform support.</td></tr></tbody></table></div></div>
  <div class="article-card"><h2>Drawdown rules in plain English</h2><ul><li>Trailing accounts use intraday trailing drawdown that can move with unrealized profits.</li><li>Static accounts use a fixed drawdown floor that does not move with intraday or closed profit.</li><li>EOD accounts update the threshold once per day based on end-of-day balance.</li><li>Once an account is created, DayTraders says the drawdown type cannot be changed.</li><li>All accounts must stay above the threshold to remain active.</li></ul></div>
  <div class="article-card"><h2>Payout and live-account notes</h2><ul><li>The official guide says Pro and S2F accounts keep 100% of profits, while live funded accounts use an 80/20 split.</li><li>Live payout requests require the trailing drawdown to lock at the initial balance.</li><li>Live accounts require a $1,000 buffer above initial balance before unrestricted withdrawal.</li><li>Live payout processing is listed daily between 5:00 and 6:00 PM ET, subject to account conditions.</li><li>S2F accounts are simulated, not live brokerage accounts, and use account-specific payout eligibility rules.</li></ul></div>
  <div class="article-card"><h2>NQ trader takeaways</h2><p>DayTraders is worth comparing because it gives traders multiple futures-only paths instead of one rigid model. For NQ and MNQ traders, the most important choice is drawdown type: intraday trailing can punish unrealized spikes, EOD is easier to plan around, and Static is the simplest floor. Use the risk calculator before buying so the stop size fits the selected account cushion.</p><a class="btn primary" href="/calculators/">Run NQ risk calculator</a></div></article>`;
}


function renderLegendsTradingArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">All firms</a><h1>The Legends Trading: Apprentice, Elite, and Straight-to-Master rules</h1><p class="lead">The Legends Trading offers three futures funding paths: monthly Apprentice evaluations, one-time Elite evaluations, and Straight to Master accounts. The right choice depends on whether you prioritize monthly cost, no activation fee, or skipping the evaluation stage.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official sources: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">The Legends Trading official site</a>, <a href="https://thelegendstrading.com/plans" target="_blank" rel="noreferrer">plans</a>, <a href="https://knowledge.thelegendstrading.com/" target="_blank" rel="noreferrer">knowledge base</a>, and <a href="https://knowledge.thelegendstrading.com/payout-process" target="_blank" rel="noreferrer">payout policy</a>.</p><p class="disclaimer">Confirm the DUTRADING discount, account rules, activation fee, payout terms, and final checkout price on The Legends Trading before buying. The offer supplied for this link is 50% OFF Apprentice Plans and 30% OFF Elite Plans; the public site may display a separate sitewide offer.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Current DUTRADING promotion</h2><ul><li>50% OFF Apprentice Plans.</li><li>30% OFF Elite Plans.</li><li>Code to try: ${f.couponCode}.</li><li>Open the link first, apply the code at checkout, and confirm the actual discount before paying.</li></ul></div>
  <div class="article-card"><h2>Apprentice, Elite, and Straight to Master</h2><div class="table-wrap"><table><thead><tr><th>Path</th><th>Payment model</th><th>Drawdown</th><th>Consistency</th><th>Minimum days</th><th>Activation</th></tr></thead><tbody><tr><td>Apprentice</td><td>Monthly subscription</td><td>EOD trailing max loss</td><td>30%</td><td>4 days shown</td><td>$99 to $199 by size</td></tr><tr><td>Elite</td><td>One-time evaluation</td><td>EOD trailing max loss</td><td>40%</td><td>Verify current plan page</td><td>None shown</td></tr><tr><td>Straight to Master</td><td>One-time purchase</td><td>Trailing max loss</td><td>30%</td><td>10 days shown</td><td>Verify checkout and funded terms</td></tr></tbody></table></div></div>
  <div class="article-card"><h2>Apprentice account reference</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Regular monthly price shown</th><th>Profit target</th><th>EOD max loss</th><th>Max contracts / micros</th><th>Activation fee</th></tr></thead><tbody><tr><td>25K</td><td>$165</td><td>$1,500</td><td>$1,500</td><td>4 / 40</td><td>$99</td></tr><tr><td>50K</td><td>$185</td><td>$3,000</td><td>$2,000</td><td>10 / 50</td><td>$99</td></tr><tr><td>100K</td><td>$225</td><td>$6,000</td><td>$3,000</td><td>14 / 70</td><td>$149</td></tr><tr><td>150K</td><td>$320</td><td>$9,000</td><td>$4,000</td><td>17 / 85</td><td>$199</td></tr></tbody></table></div><p class="disclaimer">Apply DUTRADING and confirm the 50% Apprentice discount at checkout. Do not calculate expected billing from the table without checking the final order total.</p></div>
  <div class="article-card"><h2>Elite account reference</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Regular one-time price shown</th><th>Profit target</th><th>EOD max loss</th><th>Daily loss limit</th><th>Consistency</th></tr></thead><tbody><tr><td>25K</td><td>$99</td><td>$1,500</td><td>$1,250</td><td>None</td><td>40%</td></tr><tr><td>50K</td><td>$149</td><td>$2,700</td><td>$2,200</td><td>None</td><td>40%</td></tr><tr><td>100K</td><td>$180</td><td>$6,000</td><td>$3,000</td><td>None</td><td>40%</td></tr><tr><td>150K</td><td>$230</td><td>$9,000</td><td>$4,500</td><td>None</td><td>40%</td></tr></tbody></table></div><p class="disclaimer">Apply DUTRADING and confirm the 30% Elite discount at checkout. Elite rules differ from Apprentice rules, especially consistency and activation-fee treatment.</p></div>
  <div class="article-card"><h2>Payout notes</h2><ul><li>The official payout policy lists a 90/10 trader/company split.</li><li>Payout requests may be made up to twice per month during listed request windows.</li><li>The first payout requires 10 individual active trading days.</li><li>Later payout requests require at least 10 active trading days between requests.</li><li>The first and second payouts list a $1,000 minimum, with account-size balance thresholds and payout caps.</li><li>The account must be above the trailing drawdown level and meet the current consistency rule before a request can be approved.</li></ul></div>
  <div class="article-card"><h2>NQ trader takeaways</h2><p>The Legends Trading gives NQ traders several ways to enter, but the plan labels hide meaningful rule differences. Apprentice has monthly billing, 30% consistency, and activation fees. Elite uses one-time pricing, no evaluation daily loss limit, 40% consistency, and no activation fee shown. Straight to Master skips the normal challenge path but has its own trailing-loss and minimum-day rules. Compare the full cost and size NQ against the actual drawdown, not the advertised maximum contract count.</p><a class="btn primary" href="/calculators/">Run NQ risk calculator</a></div></article>`;
}


function renderEarn2TradeArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>Earn2Trade: Trader Career Path and Gauntlet Mini rules for futures traders</h1><p class="lead">Earn2Trade is a legacy futures evaluation firm with two main programs: Trader Career PathÂ® for progression and The Gauntlet Miniâ„¢ for a direct target-size evaluation.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official source: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">${f.officialUrl}</a></p><p class="disclaimer">Earn2Trade frequently advertises limited-time discounts. Confirm the current monthly price, reset fee, activation terms, and withdrawal rules before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Earn2Trade at a glance</h2><ul><li>Products covered: Trader Career PathÂ® and The Gauntlet Miniâ„¢.</li><li>Minimum trading days: 10 days.</li><li>Rules shown on product pages: reach profit goal, maintain consistency, trade only during approved times, do not reach/dip below daily loss limit, do not reach/dip below EOD trailing drawdown, and follow progression ladder.</li><li>Supported platforms shown: Rithmic, NinjaTrader, Finamark, Tradovate, TradingView, and R Trader Pro.</li><li>Allowed instruments: futures products only on CME, COMEX, NYMEX, and CBOT.</li></ul></div>
  <div class="article-card"><h2>Trader Career PathÂ® pricing and evaluation rules</h2><div class="table-wrap"><table><thead><tr><th>Plan</th><th>Price</th><th>Virtual capital</th><th>Profit goal</th><th>EOD drawdown</th><th>Daily loss</th><th>Max contracts</th><th>Reset</th></tr></thead><tbody><tr><td>TCP25</td><td>$150/mo</td><td>$25,000</td><td>$1,750</td><td>$1,500</td><td>$550</td><td>3</td><td>$100 shown</td></tr><tr><td>TCP50</td><td>$190/mo</td><td>$50,000</td><td>$3,000</td><td>$2,000</td><td>$1,100</td><td>6</td><td>$100 shown</td></tr><tr><td>TCP100</td><td>$350/mo</td><td>$100,000</td><td>$6,000</td><td>$3,500</td><td>$2,200</td><td>12</td><td>$100 fixed for TCP100</td></tr></tbody></table></div><ul><li>Each TCP subscription includes a free reset when rebilled.</li><li>TCP reset page text says TCP25/TCP50 reset pricing can be dynamic based on promotions and below the current new-subscription price.</li><li>No upfront activation fee; the one-time $139 activation fee is deducted only from first successful withdrawal.</li></ul></div>
  <div class="article-card"><h2>Trader Career PathÂ® progression path</h2><p>Earn2Trade positions TCP as a step-up career path. The product progression is generally presented as:</p><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Capital</th><th>Profit target</th><th>Drawdown</th><th>Daily loss</th><th>Max contracts</th></tr></thead><tbody><tr><td>Evaluation</td><td>$25K / $50K / $100K starting choice</td><td>Based on chosen plan</td><td>EOD</td><td>Based on chosen plan</td><td>3 / 6 / 12</td></tr><tr><td>LiveSimÂ® or Live</td><td>Same as passed evaluation</td><td>Same as evaluation</td><td>LiveSimÂ® EOD / Live trailing</td><td>Same as evaluation</td><td>Same as evaluation</td></tr><tr><td>Live upgrade</td><td>$50,000</td><td>$3,000</td><td>$2,000 trailing</td><td>$1,100</td><td>6</td></tr><tr><td>Live upgrade</td><td>$100,000</td><td>$6,000</td><td>$3,500 trailing</td><td>$2,200</td><td>12</td></tr><tr><td>Live upgrade</td><td>$200,000</td><td>$11,000</td><td>Drawdown fixed to $194,000</td><td>$4,400</td><td>16</td></tr></tbody></table></div><p class="disclaimer">Homepage copy says Trader Career Path can scale up to $400K with fixed drawdown, but the visible product progression table listed through the $200K stage and then says a custom offer may be made.</p></div>
  <div class="article-card"><h2>The Gauntlet Miniâ„¢ pricing and rules</h2><div class="table-wrap"><table><thead><tr><th>Plan</th><th>Price</th><th>Virtual capital</th><th>Profit goal</th><th>EOD drawdown</th><th>Daily loss</th><th>Max contracts</th><th>Reset</th></tr></thead><tbody><tr><td>GAU50</td><td>$170/mo</td><td>$50,000</td><td>$3,000</td><td>$2,000</td><td>$1,100</td><td>6</td><td>$100</td></tr><tr><td>GAU100</td><td>$315/mo</td><td>$100,000</td><td>$6,000</td><td>$3,500</td><td>$2,200</td><td>12</td><td>$100</td></tr><tr><td>GAU150</td><td>$375/mo</td><td>$150,000</td><td>$9,000</td><td>$4,500</td><td>$3,300</td><td>15</td><td>$130</td></tr><tr><td>GAU200</td><td>$550/mo</td><td>$200,000</td><td>$11,000</td><td>$6,000</td><td>$4,400</td><td>16</td><td>$155</td></tr></tbody></table></div><ul><li>Gauntlet Mini is described as a single-phase evaluation.</li><li>After passing, the funded account matches the selected evaluation size.</li><li>No upfront activation fee; free trading platforms and education library.</li></ul></div>
  <div class="article-card"><h2>Funded account, withdrawals, and fees</h2><ul><li>After passing, Earn2Trade says traders receive a certificate and can choose a LiveSimÂ® or Live funded account with the same capital.</li><li>Profit split shown: 80%.</li><li>Homepage says withdrawals are weekly from $100+ with no additional performance target required to withdraw.</li><li>Activation fee: one-time $139 deducted only from the first successful withdrawal, not paid upfront.</li><li>Commissions vary by instrument and are provided upon account activation depending on Tradovate/Rithmic/provider/platform.</li></ul></div>
  <div class="article-card"><h2>NQ trader takeaways</h2><p>Earn2Trade is more structured than the newer â€œfast payoutâ€ firms. The 10-day minimum, daily loss limits, progression ladder, consistency rule, and EOD/trailing drawdown distinctions matter for NQ traders. Think of Earn2Trade as a legacy/structured alternative, not the cheapest or fastest route.</p><a class="btn primary" href="/calculators/">Run NQ risk calculator</a></div></article>`;
}

function renderLucidArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>Lucid Trading: Pro, Flex, Direct, and LucidLive path for futures traders</h1><p class="lead">Use LucidTrading.com for Lucid's current futures prop firm offer. Older LucidFunding.com references may point to a parked-domain page instead.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official source: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">${f.officialUrl}</a></p><p class="disclaimer">Lucid Trading prices, coupon codes, and live-capital terms can change. Confirm the final checkout price and current funded-account rules before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Important domain note</h2><p>LucidTrading.com is the site used in this guide. Be careful with old references to â€œLucid Trader Fundingâ€ or â€œLucidFunding.com,â€ because those may not point to the current Lucid Trading offer.</p></div>
  <div class="article-card"><h2>LucidPro evaluation pricing and rules</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Price shown</th><th>Coupon price</th><th>Reset</th><th>Target</th><th>Max loss</th><th>DLL</th><th>Max size</th></tr></thead><tbody><tr><td>25K Pro</td><td>$135</td><td>$94.50</td><td>$90</td><td>$1,250</td><td>$1,000 EOD</td><td>None</td><td>2 mini / 20 micro</td></tr><tr><td>50K Pro</td><td>$185</td><td>$129.50</td><td>$120</td><td>$3,000</td><td>$2,000 EOD</td><td>$1,200</td><td>4 mini / 40 micro</td></tr><tr><td>100K Pro</td><td>$285</td><td>$199.50</td><td>$180</td><td>$6,000</td><td>$3,000 EOD</td><td>$1,800</td><td>6 mini / 60 micro</td></tr><tr><td>150K Pro</td><td>$370</td><td>$259.00</td><td>$245</td><td>$9,000</td><td>$4,500 EOD</td><td>$2,700</td><td>10 mini / 100 micro</td></tr></tbody></table></div><ul><li>Account activation fee: free.</li><li>Trader dashboard: realtime.</li><li>Homepage says Pro can pass in as little as one day.</li></ul></div>
  <div class="article-card"><h2>LucidFlex evaluation pricing and rules</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Price shown</th><th>Coupon price</th><th>Reset</th><th>Target</th><th>Max loss</th><th>Consistency</th><th>Max size</th></tr></thead><tbody><tr><td>25K Flex</td><td>$100</td><td>$70.00</td><td>$60</td><td>$1,250</td><td>$1,000 EOD</td><td>50%</td><td>2 mini / 20 micro</td></tr><tr><td>50K Flex</td><td>$140</td><td>$98.00</td><td>$95</td><td>$3,000</td><td>$2,000 EOD</td><td>50%</td><td>4 mini / 40 micro</td></tr><tr><td>100K Flex</td><td>$225</td><td>$157.50</td><td>$140</td><td>$6,000</td><td>$3,000 EOD</td><td>50%</td><td>6 mini / 60 micro</td></tr><tr><td>150K Flex</td><td>$420</td><td>$294.00</td><td>$280</td><td>$9,000</td><td>$4,500 EOD</td><td>50%</td><td>10 mini / 100 micro</td></tr></tbody></table></div><ul><li>Flex shows no Daily Loss Limit.</li><li>Flex shows no consistency in funded.</li><li>Account activation fee: free.</li></ul></div>
  <div class="article-card"><h2>LucidDirect straight-to-funded pricing</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Price shown</th><th>Coupon price</th><th>Max loss</th><th>DLL below trail</th><th>LucidScale DLL above trail</th><th>Consistency</th><th>Max size</th></tr></thead><tbody><tr><td>25K Direct</td><td>$340</td><td>$238.00</td><td>$1,000 EOD</td><td>â€”</td><td>â€”</td><td>20%</td><td>2 mini / 20 micro</td></tr><tr><td>50K Direct</td><td>$520</td><td>$364.00</td><td>$2,000 EOD</td><td>$1,200</td><td>60% of Peak EOD Balance</td><td>20%</td><td>4 mini / 40 micro</td></tr><tr><td>100K Direct</td><td>$700</td><td>$490.00</td><td>$3,500 EOD</td><td>$2,100</td><td>60% of Peak EOD Balance</td><td>20%</td><td>6 mini / 60 micro</td></tr><tr><td>150K Direct</td><td>$840</td><td>$588.00</td><td>$5,000 EOD</td><td>$3,000</td><td>60% of Peak EOD Balance</td><td>20%</td><td>10 mini / 100 micro</td></tr></tbody></table></div><ul><li>Direct is straight to funded.</li><li>Minimum days to payout: 5.</li><li>Maximum accounts: 5.</li><li>Trader dashboard: realtime.</li></ul></div>
  <div class="article-card"><h2>Funded rules and LucidLive path</h2><ul><li>Homepage says 90/10 profit split, no payout windows, clear/simple rules, and 15-minute average payout time.</li><li>About page says payouts and activations take minutes, there are no monthly billing charges, and Lucid offers platform freedom.</li><li>About page says LucidDirect skips the evaluation, uses End of Day drawdown, and has a DLL that scales as the trader earns.</li><li>Example listed from 25K Pro funded rules: payout profit target $250, max loss $1,000, 40% consistency, max size 2 mini / 20 micro, 3 days to payout, free activation, one-day pass eval, and 5 payouts to live.</li><li>LucidLive path: after a successful track record, trader can be moved to live brokerage, withdraw daily, swing trade, and work directly with risk team.</li></ul></div>
  <div class="article-card"><h2>Official Lucid pages</h2><ul><li>https://lucidtrading.com/</li><li>https://lucidtrading.com/about-us/</li><li>https://lucidtrading.com/affiliate/</li><li>https://lucidfunding.com/ has appeared as a parked-domain sale page, not the active prop firm site.</li></ul></div>
  <div class="article-card"><h2>Why this matters for NQ traders</h2><p>Lucid Trading is attractive because it combines EOD drawdown, no activation fees, fast payout messaging, and a direct-funded option. The biggest NQ-specific caution is that Pro and Direct still have daily loss limits on larger accounts, while Flex has a 50% evaluation consistency rule. For NQ traders, Flex may be simpler if you want no DLL in funded, while Pro may fit traders who want one-day evaluation potential.</p><a class="btn primary" href="/calculators/">Run drawdown calculator</a></div></article>`;
}

function renderBulenoxArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>Bulenox: Qualification, Master, and Funded Account rules for futures traders</h1><p class="lead">Bulenox's official homepage and help center show a monthly Qualification Account model with two drawdown choices: No Scaling trailing drawdown, or EOD drawdown with scaling and a daily loss limit.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official source: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">${f.officialUrl}</a></p><p class="disclaimer">Bulenox pricing, coupon codes, activation fees, and payout rules can change. Confirm the final checkout price and current rule page before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Bulenox account tiers</h2><div class="table-wrap"><table><thead><tr><th>Account</th><th>Max contracts</th><th>Profit target</th><th>Drawdown</th><th>Monthly price shown</th></tr></thead><tbody><tr><td>10K</td><td>5 micros</td><td>$1,000</td><td>$1,000</td><td>$115/month</td></tr><tr><td>25K</td><td>3 contracts</td><td>$1,500</td><td>$1,500</td><td>$145/month</td></tr><tr><td>50K</td><td>7 contracts</td><td>$3,000</td><td>$2,500</td><td>$125/month with $50OFF coupon; $175 listed before coupon</td></tr><tr><td>100K</td><td>12 contracts</td><td>$6,000</td><td>$3,000</td><td>$155/month with $60OFF coupon; $215 listed before coupon</td></tr><tr><td>150K</td><td>15 contracts</td><td>$9,000</td><td>$4,500</td><td>$325/month</td></tr><tr><td>250K</td><td>25 contracts</td><td>$15,000</td><td>$5,500</td><td>$535/month</td></tr></tbody></table></div><p class="disclaimer">Each tier has been offered with two choices: â€œOpt 1: No Scaling Accountâ€ or â€œOpt 2: EOD Account.â€ Confirm the current option names before buying.</p></div>
  <div class="article-card"><h2>Qualification Account rules</h2><ul><li>No minimum trading days are required to get a Master Account; the trader must reach the profit target and have at least one completed trading day for review.</li><li>All open positions must be closed before 15:59 CT/CST.</li><li>NQ and MNQ are listed as permitted futures instruments.</li><li>One standard contract equals 10 micro contracts.</li><li>Using trade copiers, algorithms, strategies, or bots is not forbidden, but Bulenox says it is not responsible for third-party software issues.</li><li>Reset cost is $78 outside the free reset on billing date; reset does not change the subscription expiration date.</li></ul></div>
  <div class="article-card"><h2>Two drawdown options</h2><ul><li><b>Option 1 No Scaling:</b> trailing drawdown follows current balance, including realized and unrealized gains, records in real time, and includes commissions.</li><li><b>Option 2 EOD:</b> EOD drawdown updates when the account reaches a new high balance at the end of the trading day.</li><li>For Master Accounts, trailing/EOD drawdown stops moving when it reaches the initial starting balance + $100.</li><li>EOD Daily Loss Limits: 10K $400, 25K $500, 50K $1,100, 100K $2,200, 150K $3,300, 250K $4,500.</li><li>DLL is based on P&L including commissions and real-time/unrealized trades. Hitting it suspends the account for the rest of the trading day and is not counted as a rule violation.</li></ul></div>
  <div class="article-card"><h2>EOD scaling and Master fees</h2><ul><li>10K EOD has no scaling and max 5 micro contracts.</li><li>25K EOD scales from 2 contracts to 3 contracts after $1,501+ cash on hand.</li><li>50K EOD scales 2 â†’ 4 â†’ 7 contracts as cash on hand reaches $1,501 and $4,001+.</li><li>100K EOD scales 3 â†’ 5 â†’ 8 â†’ 12 contracts as cash on hand reaches $2,001, $3,001, and $5,001+.</li><li>150K EOD scales 5 â†’ 8 â†’ 10 â†’ 15 contracts as cash on hand reaches $4,001, $8,001, and $12,001+.</li><li>Master activation fees listed: 25K $143, 50K $148, 100K $248, 150K $498, 250K $898. The Qualification page also lists 10K at $98 for Option 2.</li></ul></div>
  <div class="article-card"><h2>Master and Funded payout rules</h2><ul><li>Master payouts: first $10,000 earned is paid 100% to the trader; after the first $10,000, trader receives 90% and Bulenox commission is 10%.</li><li>Master payout requests can be submitted any time during the calendar month, and payouts are processed weekly on Wednesdays.</li><li>Master payout processing requires at least 10 individual trading days.</li><li>Master minimum withdrawal is $1,000; first-three-payout maximums: 25K $1,000, 50K $1,500, 100K $1,750, 150K $2,000, 250K $2,500. After the third payout there is no maximum withdrawal limit.</li><li>Master payout consistency is 40%: the best single trading day must not exceed 40% of total profit balance at withdrawal request.</li><li>After three successful Master payouts, a trader may transition to a Funded Account at Risk Management's sole discretion. Funded Account reward request requires at least 5 trading days.</li></ul></div>
  <div class="article-card"><h2>Official Bulenox pages</h2><ul><li>https://bulenox.com/</li><li>https://bulenox.com/help/qualification-account/</li><li>https://bulenox.com/help/master-account/</li><li>https://bulenox.com/help/funded-account/</li><li>https://bulenox.com/help/subscription-and-payment/</li><li>https://bulenox.com/help/frequently-asked-questions/</li></ul></div>
  <div class="article-card"><h2>Why this matters for NQ traders</h2><p>Bulenox can look cheap, especially with homepage coupons, but the drawdown option matters more than the sticker price. The No Scaling option uses real-time trailing drawdown including unrealized gains, which is dangerous for NQ runners. The EOD option is usually easier to reason about, but it adds daily loss limits and scaling. NQ traders should treat the 50K/100K EOD accounts differently from No Scaling accounts.</p><a class="btn primary" href="/calculators/">Run drawdown calculator</a></div></article>`;
}

function renderApexArticle(f){
  return `<article class="article wrap"><a class="btn" href="/firms/">â† All firms</a><h1>Apex Trader Funding: EOD vs Intraday drawdown</h1><p class="lead">Apex changed materially in 2026. Treat it as two different products: EOD trailing drawdown accounts and intraday trailing drawdown accounts.</p>
  <div class="article-card verify-card"><h2>Source review</h2><p><span class="pill ${verificationClass(f)}">${verificationLabel(f)}</span></p><p>Official source: <a href="${f.officialUrl}" target="_blank" rel="noreferrer">${f.officialUrl}</a></p><p class="disclaimer">Apex account rules, payout terms, and checkout discounts can change. Confirm current EOD rules and final pricing on the official Apex site before buying.</p></div>
  ${affiliateCard(f)}
  <div class="article-card"><h2>Apex EOD rule snapshot</h2><ul><li><b>EOD drawdown:</b> calculated once per trading day at 4:59:59 PM ET, based on the account's closing balance.</li><li><b>Enforcement:</b> once calculated, the EOD threshold is enforced during the next trading session; touching or falling below it fails the evaluation or closes the PA.</li><li><b>No intraday trailing drawdown:</b> Apex's EOD pages state there is no intraday trailing drawdown on EOD accounts.</li><li><b>Daily Loss Limit:</b> EOD evaluations and EOD PAs have DLLs enforced intraday by account size.</li><li><b>Evaluation pass:</b> no minimum trading days required; a trader may pass in one day if the profit target is reached and rules are respected.</li><li><b>PA activation window:</b> after passing, Apex says traders have 7 calendar days to activate the corresponding EOD Performance Account.</li></ul></div>
  <div class="article-card"><h2>Apex EOD account specs</h2><div class="table-wrap"><table><thead><tr><th>Size</th><th>Profit target</th><th>Max drawdown</th><th>Daily loss limit</th><th>Eval contracts</th><th>Retail EOD price</th></tr></thead><tbody><tr><td><strong>$25K EOD</strong></td><td>$1,500</td><td>$1,000</td><td>$500</td><td>4</td><td>$177</td></tr><tr><td><strong>$50K EOD</strong></td><td>$3,000</td><td>$2,000</td><td>$1,000</td><td>6</td><td>$197</td></tr><tr><td><strong>$100K EOD</strong></td><td>$6,000</td><td>$3,000</td><td>$1,500</td><td>8</td><td>$297</td></tr><tr><td><strong>$150K EOD</strong></td><td>$9,000</td><td>$4,000</td><td>$2,000</td><td>12</td><td>$397</td></tr></tbody></table></div><p class="disclaimer">Apex EOD specs can change. Confirm current pricing, coupons, and account rules on the official Apex site before buying.</p></div>
  <div class="article-card"><h2>Apex EOD payout rules</h2><ul><li>Approved EOD PA payouts are listed as a 100% payout split.</li><li>Minimum 5 qualifying trading days are required before payout request.</li><li>Minimum daily profit per qualifying day: $100 on 25K, $250 on 50K, $300 on 100K, $350 on 150K.</li><li>50% consistency rule applies: no single profitable day may be 50% or more of total profit since the last approved payout.</li><li>Minimum payout request is $500.</li><li>Each EOD Performance Account may receive a maximum of six payouts, then the PA is closed.</li></ul></div><div class="article-card"><h2>Why this matters for NQ traders</h2><p>On an intraday trailing account, an unrealized NQ runner can push the high-water mark up before you close the trade. If price reverses, your floor may already be higher. On Apex-style EOD drawdown, Apex's official EOD pages state there is no intraday trailing drawdown; the threshold is calculated from the end-of-day balance and enforced afterward.</p><p>For most NQ traders who hold trades for more than a few seconds, EOD is usually easier to manage. Pure tick scalpers may still compare intraday accounts if they are flat quickly.</p><a class="btn primary" href="/calculators/">Run EOD drawdown calculator</a></div>
  <div class="article-card"><h2>Official Apex pages</h2><ul><li>https://apextraderfunding.com/help-center/eod-trailing-drawdown-accounts/eod-evaluations/</li><li>https://apextraderfunding.com/help-center/eod-trailing-drawdown-accounts/eod-drawdown-explained/</li><li>https://apextraderfunding.com/help-center/eod-trailing-drawdown-accounts/eod-performance-accounts-pa/</li><li>https://apextraderfunding.com/help-center/eod-trailing-drawdown-accounts/eod-payouts/</li></ul></div></article>`;
}

function renderDisclaimers(){return `<article class="article wrap"><h1>Disclosures</h1><div class="article-card"><h2>Affiliate disclosure</h2><p>This site may earn commissions when visitors click affiliate links or use discount codes. Recommendations are based on rule fit, account structure, trader risk, and official-source review. Affiliate compensation may exist, but it should not replace your own rule review or final checkout confirmation.</p></div><div class="article-card"><h2>Educational only</h2><p>Futures Prop Edge is for education and comparison only. It is not financial advice, investment advice, tax advice, legal advice, or a promise that users will pass an evaluation, receive a payout, qualify for live capital, or make money.</p></div><div class="article-card"><h2>Futures and prop-firm risk</h2><p>Futures trading is risky, leveraged, and not suitable for every trader. Prop-firm evaluations and simulated funded accounts can involve fees, resets, activation costs, drawdown rules, payout restrictions, consistency rules, and account closures. Only trade capital and fees you can afford to lose.</p></div><div class="article-card"><h2>Rule-change policy</h2><p>Prop firm rules, prices, discounts, payout policies, platform access, country restrictions, and account availability can change frequently. Use the last-reviewed date and official-rule links as a starting point, then verify the latest terms directly with the firm before buying.</p></div><div class="article-card"><h2>Checklist and analytics</h2><p>The checklist unlock is instant. Submitting the form may add your email and trading focus to the site's email provider so future rule updates can be sent. The browser keeps only checklist status metadata, not the raw email. Form and download events may be measured without sending the raw email as an analytics event.</p></div><div class="article-card"><h2>Before you use this site</h2><ul><li>Verify each prop firm rule directly from official sources before buying.</li><li>Recheck every offer, coupon code, and official rule page before purchasing an account.</li><li>Read the affiliate disclosure, educational disclaimer, risk disclosure, and rule-change policy before relying on any comparison.</li><li>The checklist is provided as an educational planning aid, not a promise of account approval, payouts, live funding, or trading profits.</li></ul></div></article>`}

function renderPrivacy(){return `<article class="article wrap"><a class="btn" href="/">Home</a><h1>Privacy Policy</h1><p class="lead">Futures Prop Edge collects only the information needed to run the site, measure usage, and deliver the checklist/newsletter experience.</p><div class="article-card"><h2>Email and checklist signup</h2><p>When you submit the checklist form, your email address and selected trading focus may be sent to our email provider, currently MailerLite, so you can receive checklist access and future rule/risk updates. The site stores checklist status metadata in your browser, but it does not store your raw email in browser local storage.</p></div><div class="article-card"><h2>Analytics</h2><p>The site may use Vercel Analytics, Google Analytics, and Microsoft Clarity to understand page views, button clicks, calculator usage, and signup/download events. Analytics events should not include your raw email address.</p></div><div class="article-card"><h2>Affiliate links</h2><p>Outbound affiliate links may use tracking parameters or redirects. If you buy after clicking one of those links or using a listed code, this site may earn a commission.</p></div><div class="article-card"><h2>Your choices</h2><p>You can unsubscribe from emails using the unsubscribe link in any email. You can also clear browser storage or block analytics through your browser settings.</p></div></article>`}

function renderTerms(){return `<article class="article wrap"><a class="btn" href="/">Home</a><h1>Terms of Use</h1><p class="lead">Use this site as an educational comparison tool, not as financial advice or a guarantee that any prop firm account will be right for you.</p><div class="article-card"><h2>Educational content only</h2><p>Futures Prop Edge provides rule summaries, calculators, checklists, and comparison notes for funded futures traders. Nothing here is financial, investment, tax, or legal advice.</p></div><div class="article-card"><h2>Risk and responsibility</h2><p>Futures trading and prop-firm evaluations involve substantial risk. You are responsible for verifying current rules, prices, restrictions, payout policies, and checkout terms directly with each firm before purchasing.</p></div><div class="article-card"><h2>No guarantees</h2><p>The site does not guarantee evaluation passes, payouts, live funding, profits, discounts, or account approval. Rules and offers may change after a page was reviewed.</p></div><div class="article-card"><h2>Affiliate compensation</h2><p>Some links and codes are affiliate offers. Compensation may be earned, but you should still compare rule fit and confirm final checkout pricing before buying.</p></div></article>`}

function renderBestNqArticle(){
  const recommended = firms.filter(isRecommended);
  return `<article class="article wrap"><a class="btn" href="/">Home</a><h1>Best funded futures prop firms for NQ traders</h1><p class="lead">NQ and MNQ traders need more than a cheap challenge. The real question is whether the drawdown, daily loss, payout, and contract rules match the way you trade Nasdaq futures.</p><div class="article-card"><h2>Quick picks</h2><div class="finder-grid">${recommended.map(f=>`<article class="finder-card"><div class="finder-card-top"><div><h3>${f.name}</h3><p>${f.fit}</p></div>${recommendationBadge(f)}</div><div class="finder-tags">${firmTraits(f).map(t=>`<span>${t}</span>`).join('')}</div><p>${couponText(f)}</p>${affiliateActions(f,true)}</article>`).join('')}</div></div><div class="article-card"><h2>How to choose for NQ</h2><ul><li><b>Start with drawdown:</b> Static and EOD drawdown are easier to plan around than real-time intraday trailing when NQ moves fast.</li><li><b>Respect daily loss limits:</b> A normal NQ stop can consume a small DLL quickly. Use MNQ while your cushion is thin.</li><li><b>Read payout rules:</b> Fast payout language can still include consistency rules, buffers, minimum days, caps, or live-transition discretion.</li><li><b>Confirm checkout:</b> Codes and promos can change. Always verify the final price before buying.</li></ul></div><div class="article-card"><h2>Recommended starting point</h2><p>For most NQ traders, begin with the rule fit rather than the headline price. Phidias is worth checking for static/E2L and swing-friendly Premium rules, Lucid Trading for EOD drawdown and direct-funded paths, and Bulenox for budget-focused traders who are willing to read drawdown options carefully.</p><a class="btn primary" href="/checklist/">Download the NQ checklist</a></div></article>`;
}


export {
  firms, affiliateFirms, comparisonFirms, firmBySlug, money, num, riskClass, verificationClass, verificationLabel,
  isRecommended, recommendationBadge, affiliatePrimaryLabel, affiliateHref,
  couponText, affiliateActions, affiliateCard, firmTraits, firmMatches,
  finderRecommendation, pageShell, renderHome, topMarketTape, startPathSection,
  offerBanners, guidesSection, leadMagnetSection, comparisonSection, renderCompare,
  renderChecklist, calculatorSection, renderCalculators, drawdownCalc, nqCalc,
  plannerCalc, renderFirms, renderDisclaimers, renderPrivacy, renderTerms,
  renderBestNqArticle
};
